apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-storage
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: monitoring
    name: grafana-storage
  gcePersistentDisk:
    pdName: elastic-disk
    fsType: ext4