apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kserve-triton-exporter
  labels:
    app.kubernetes.io/name: kserve-triton-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      prometheus.io/scrape: "true"
      kserve-predictor: "triton"
  namespaceSelector:
    any: true
  endpoints:
  - interval: 60s
    port: http-autometric
    path: /metrics
  - interval: 60s
    port: http-usermetric