apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: compactor
    app.kubernetes.io/instance: thanos-compactor
    app.kubernetes.io/name: thanos-compactor
    app.kubernetes.io/version: v0.39.1
  name: thanos-compactor
  namespace: monitoring
spec:
  endpoints:
    - port: http
      relabelings:
        - action: replace
          separator: /
          sourceLabels:
            - namespace
            - pod
          targetLabel: instance
  selector:
    matchLabels:
      app.kubernetes.io/component: compactor
      app.kubernetes.io/instance: thanos-compactor
      app.kubernetes.io/name: thanos-compactor 