apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: compactor
    app.kubernetes.io/instance: thanos-compactor
    app.kubernetes.io/name: thanos-compactor
    app.kubernetes.io/version: v0.39.1
  name: thanos-compactor
  namespace: monitoring 