apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: query-frontend
    app.kubernetes.io/instance: thanos-query-frontend
    app.kubernetes.io/name: thanos-query-frontend
    app.kubernetes.io/version: v0.41.0
  name: thanos-query-frontend-cache-config
  namespace: monitoring
stringData:
  cache.yaml: |-
    type: MEMCACHED
    config:
      addresses:
        - thanos-query-frontend-memcached.monitoring.svc:11211
      timeout: 500ms
      max_idle_connections: 100
      max_async_concurrency: 20
      max_async_buffer_size: 10000
type: Opaque
