apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: compactor
    app.kubernetes.io/instance: thanos-compactor
    app.kubernetes.io/name: thanos-compactor
    app.kubernetes.io/version: v0.39.1
  name: thanos-compactor
  namespace: monitoring
spec:
  ports:
    - name: http
      port: 10902
      targetPort: 10902
  selector:
    app.kubernetes.io/component: compactor
    app.kubernetes.io/instance: thanos-compactor
    app.kubernetes.io/name: thanos-compactor 