{
 "title": "Incident Monitoring",
 "description": "We commit to delivering our services as fast as possible to our customers and as a minimum within 10 minutes for extractions for 90% of all requests that are less than 10 pages and classify intent faster than 5 minutes for all of our services.\n\nFor us to better know if we do this we need a dashboard that can help us monitor this.",
 "tags": [
  "incident",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "metric",
    "label": "Metric",
    "query": "mean, median, p80, p90, p95, p99"
   },
   { "name": "time_interval", "label": "Time interval", "query": "1m, 5m, 10m, 15m, 30m, 1h, 24h" },
   {
    "name": "org",
    "label": "Organization",
    "query": {
     "query": "SELECT org_id FROM auth.organization where org_id not like '%_shadow' and org_id not like '%_demo' and org_id not like '%_qa' and org_id not like '%_temp' and org_id not like '%dummy%' and org_id not like '%test%' and org_id != 'gianlucas' and org_id != 'goautonomous' and org_id != 'goa-platform-e2e' and org_id !='ml' and org_id != 'mom' and org_id !='20b88278-21b3-4db2-a95a-1f63073b22cf' and org_id != 'rokstarorganization' and org_id !='00000002-0000-0000-0000-000000000000' and org_id != '00000003-0000-0000-0000-000000000000'"
    }
   },
   {
    "name": "intent",
    "label": "Intent",
    "query": "SELECT intent FROM metrics.events WHERE event='saga_processing_time' AND intent!='' GROUP BY intent;"
   },
   {
    "name": "threshold",
    "label": "Threshold",
    "query": "0.5 min, 1 min, 2 min, 3 min, 4 min, 5 min, 10 min, 15 min"
   }
  ]
 },
 "panels": [
  {
   "title": "Messages per queue (ready + unacked)",
   "type": "bargauge",
   "description": "Current message count in each queue. The simplest 'which queue holds how much' view.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "timeSeriesList": {
      "aliasBy": "{{metric.label.rabbitmq_queue}}",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "custom.googleapis.com/cloudamqp/rabbitmq/queue/messages",
       "AND",
       "metric.label.rabbitmq_queue",
       "=~",
       "${queue:regex}"
      ],
      "groupBys": [ "metric.label.rabbitmq_queue" ],
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "${project}"
     }
    }
   ]
  },
  {
   "title": "Mails received /s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "promQLQuery": {
      "expr": "# Just total\nsum (rate({\"__name__\"=\"mail_received_count_total\", \"org_id\"=~\"$org\"}[${__interval}]))\n",
      "projectName": "api-sandbox-goauto-11",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "api-sandbox-goauto-11",
      "view": "FULL"
     }
    }
   ]
  },
  { "title": "Processing time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Saga mail extraction timing",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH time_series AS (\r\n  SELECT\r\n    GENERATE_SERIES(\r\n      $__timeFrom() :: timestamp,\r\n      $__timeTo() :: timestamp,\r\n      '$time_interval' :: interval\r\n    ) AS date_time\r\n),\r\nevents_data AS (\r\n  SELECT\r\n    DATE_BIN('$time_interval', date_time, '2000-1-1') AS time,\r\n    AVG(CAST(value AS DECIMAL(10, 3))) AS mean\r\n  FROM\r\n    metrics.events\r\n  WHERE\r\n    event = 'saga_processing_time'\r\n    AND $__timeFilter(date_time)\r\n    AND org IN ($org)\r\n    AND intent IN ($intent)\r\n    AND (\r\n      is_qa IS NULL\r\n      OR is_qa = FALSE\r\n    )\r\n  GROUP BY\r\n    time\r\n)\r\nSELECT\r\n  date_time,\r\n  COALESCE(mean, 0) AS mean\r\nFROM\r\n  time_series\r\n  LEFT JOIN events_data ON DATE_BIN('$time_interval', date_time, '2000-1-1') = time\r\nWHERE\r\n  'mean' IN ($metric)\r\nORDER BY\r\n  date_time;"
    },
    {
     "rawSql": "WITH time_series AS (\r\n  SELECT\r\n    GENERATE_SERIES(\r\n      $__timeFrom() :: timestamp,\r\n      $__timeTo() :: timestamp,\r\n      '$time_interval' :: interval\r\n    ) AS date_time\r\n),\r\nevents_data AS (\r\n  SELECT\r\n    DATE_BIN('$time_interval', date_time, '2000-1-1') AS time,\r\n    PERCENTILE_CONT(0.5) WITHIN GROUP (\r\n      ORDER BY\r\n        CAST(value AS DECIMAL(10, 3))\r\n    ) AS median\r\n  FROM\r\n    metrics.events\r\n  WHERE\r\n    event = 'saga_processing_time'\r\n    AND $__timeFilter(date_time)\r\n    AND org IN ($org)\r\n    AND intent IN ($intent)\r\n    AND (\r\n      is_qa IS NULL\r\n      OR is_qa = FALSE\r\n    )\r\n  GROUP BY\r\n    time\r\n)\r\nSELECT\r\n  date_time,\r\n  COALESCE(median, 0) AS median\r\nFROM\r\n  time_series\r\n  LEFT JOIN events_data ON DATE_BIN('$time_interval', date_time, '2000-1-1') = time\r\nWHERE\r\n  'median' IN ($metric)\r\nORDER BY\r\n  date_time;"
    },
    {
     "rawSql": "WITH time_series AS (\r\n  SELECT\r\n    GENERATE_SERIES(\r\n      $__timeFrom() :: timestamp,\r\n      $__timeTo() :: timestamp,\r\n      '$time_interval' :: interval\r\n    ) AS date_time\r\n),\r\nevents_data AS (\r\n  SELECT\r\n    DATE_BIN('$time_interval', date_time, '2000-1-1') AS time,\r\n    PERCENTILE_CONT(0.8) WITHIN GROUP (\r\n      ORDER BY\r\n        CAST(value AS DECIMAL(10, 3))\r\n    ) AS p80\r\n  FROM\r\n    metrics.events\r\n  WHERE\r\n    event = 'saga_processing_time'\r\n    AND $__timeFilter(date_time)\r\n    AND org IN ($org)\r\n    AND intent IN ($intent)\r\n    AND (\r\n      is_qa IS NULL\r\n      OR is_qa = FALSE\r\n    )\r\n  GROUP BY\r\n    time\r\n)\r\nSELECT\r\n  date_time,\r\n  COALESCE(p80, 0) AS p80\r\nFROM\r\n  time_series\r\n  LEFT JOIN events_data ON DATE_BIN('$time_interval', date_time, '2000-1-1') = time\r\nWHERE\r\n  'p80' IN ($metric)\r\nORDER BY\r\n  date_time;"
    },
    {
     "rawSql": "WITH time_series AS (\r\n  SELECT\r\n    GENERATE_SERIES(\r\n      $__timeFrom() :: timestamp,\r\n      $__timeTo() :: timestamp,\r\n      '$time_interval' :: interval\r\n    ) AS date_time\r\n),\r\nevents_data AS (\r\n  SELECT\r\n    DATE_BIN('$time_interval', date_time, '2000-1-1') AS time,\r\n    PERCENTILE_CONT(0.9) WITHIN GROUP (\r\n      ORDER BY\r\n        CAST(value AS DECIMAL(10, 3))\r\n    ) AS p90\r\n  FROM\r\n    metrics.events\r\n  WHERE\r\n    event = 'saga_processing_time'\r\n    AND $__timeFilter(date_time)\r\n    AND org IN ($org)\r\n    AND intent IN ($intent)\r\n    AND (\r\n      is_qa IS NULL\r\n      OR is_qa = FALSE\r\n    )\r\n  GROUP BY\r\n    time\r\n)\r\nSELECT\r\n  date_time,\r\n  COALESCE(p90, 0) AS p90\r\nFROM\r\n  time_series\r\n  LEFT JOIN events_data ON DATE_BIN('$time_interval', date_time, '2000-1-1') = time\r\nWHERE\r\n  'p90' IN ($metric)\r\nORDER BY\r\n  date_time;"
    },
    {
     "rawSql": "WITH time_series AS (\r\n  SELECT\r\n    GENERATE_SERIES(\r\n      $__timeFrom() :: timestamp,\r\n      $__timeTo() :: timestamp,\r\n      '$time_interval' :: interval\r\n    ) AS date_time\r\n),\r\nevents_data AS (\r\n  SELECT\r\n    DATE_BIN('$time_interval', date_time, '2000-1-1') AS time,\r\n    PERCENTILE_CONT(0.95) WITHIN GROUP (\r\n      ORDER BY\r\n        CAST(value AS DECIMAL(10, 3))\r\n    ) AS p95\r\n  FROM\r\n    metrics.events\r\n  WHERE\r\n    event = 'saga_processing_time'\r\n    AND $__timeFilter(date_time)\r\n    AND org IN ($org)\r\n    AND intent IN ($intent)\r\n    AND (\r\n      is_qa IS NULL\r\n      OR is_qa = FALSE\r\n    )\r\n  GROUP BY\r\n    time\r\n)\r\nSELECT\r\n  date_time,\r\n  COALESCE(p95, 0) AS p95\r\nFROM\r\n  time_series\r\n  LEFT JOIN events_data ON DATE_BIN('$time_interval', date_time, '2000-1-1') = time\r\nWHERE\r\n  'p95' IN ($metric)\r\nORDER BY\r\n  date_time;"
    },
    {
     "rawSql": "WITH time_series AS (\r\n  SELECT\r\n    GENERATE_SERIES(\r\n      $__timeFrom() :: timestamp,\r\n      $__timeTo() :: timestamp,\r\n      '$time_interval' :: interval\r\n    ) AS date_time\r\n),\r\nevents_data AS (\r\n  SELECT\r\n    DATE_BIN('$time_interval', date_time, '2000-1-1') AS time,\r\n    PERCENTILE_CONT(0.99) WITHIN GROUP (\r\n      ORDER BY\r\n        CAST(value AS DECIMAL(10, 3))\r\n    ) AS p99\r\n  FROM\r\n    metrics.events\r\n  WHERE\r\n    event = 'saga_processing_time'\r\n    AND $__timeFilter(date_time)\r\n    AND org IN ($org)\r\n    AND intent IN ($intent)\r\n    AND (\r\n      is_qa IS NULL\r\n      OR is_qa = FALSE\r\n    )\r\n  GROUP BY\r\n    time\r\n)\r\nSELECT\r\n  date_time,\r\n  COALESCE(p99, 0) AS p99\r\nFROM\r\n  time_series\r\n  LEFT JOIN events_data ON DATE_BIN('$time_interval', date_time, '2000-1-1') = time\r\nWHERE\r\n  'p99' IN ($metric)\r\nORDER BY\r\n  date_time;"
    },
    {
     "aliasBy": "Orchestrator",
     "timeSeriesQuery": {
      "graphPeriod": "$time_interval",
      "projectName": "api-sandbox-goauto-11",
      "query": "fetch prometheus_target\n| metric 'prometheus.googleapis.com/extraction_duration_milliseconds/histogram'\n| align delta(1m)\n| every 1m\n| group_by [],\n    [value_extraction_duration_milliseconds_mean:\n       mean(value.extraction_duration_milliseconds) / 1000]"
     }
    }
   ]
  },
  {
   "title": "Mail extraction timings",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(CAST(value AS DECIMAL(10, 3))) AS \"mean\",\n  PERCENTILE_CONT(0.50) WITHIN GROUP (ORDER BY CAST(value AS DECIMAL(10, 3))) AS \"median\",\n  PERCENTILE_CONT(0.90) WITHIN GROUP (ORDER BY CAST(value AS DECIMAL(10, 3))) AS \"p90\",\n  PERCENTILE_CONT(0.95) WITHIN GROUP (ORDER BY CAST(value AS DECIMAL(10, 3))) AS \"p95\",\n  PERCENTILE_CONT(0.99) WITHIN GROUP (ORDER BY CAST(value AS DECIMAL(10, 3))) AS \"p99\"\nFROM\n  metrics.events\nWHERE\n  event = 'saga_processing_time'\n  AND $__timeFilter(date_time)\n  AND org IN ($org)\n  AND intent IN ($intent)\n  AND (\n      is_qa IS NULL\n      OR is_qa = FALSE\n  );"
    }
   ]
  },
  {
   "title": "Mails in processing per second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "metric.type",
       "=",
       "prometheus.googleapis.com/processing_started_count_total/counter"
      ],
      "groupBys": [],
      "perSeriesAligner": "ALIGN_NONE",
      "preprocessor": "rate",
      "projectName": "api-sandbox-goauto-11",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Processed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH time_series AS (\r\n  SELECT\r\n    GENERATE_SERIES(\r\n      $__timeFrom(),\r\n      $__timeTo(),\r\n      '$time_interval'::interval\r\n    ) AS dt\r\n),\r\nevents_data AS (\r\n  SELECT\r\n    DATE_BIN('$time_interval', date_time, '1970-01-01Z'::timestamptz) AS time,\r\n    COUNT(value) AS count\r\n  FROM\r\n    metrics.events\r\n  WHERE\r\n    event = 'saga_processing_time'\r\n    AND $__timeFilter(date_time)\r\n    AND org IN ($org)\r\n    AND intent IN ($intent)\r\n    AND (\r\n      is_qa IS NULL\r\n      OR is_qa = FALSE\r\n    )\r\n  GROUP BY time\r\n)\r\nSELECT\r\n  dt AS \"time\",\r\n  COALESCE(ed.count, 0) AS \"ML logs\"\r\nFROM\r\n  time_series ts\r\n  LEFT JOIN events_data ed ON DATE_BIN('$time_interval', ts.dt, '1970-01-01Z'::timestamptz) = ed.time\r\nORDER BY 1;"
    },
    {
     "aliasBy": "GCP prometheus",
     "timeSeriesQuery": {
      "graphPeriod": "$time_interval",
      "projectName": "api-sandbox-goauto-11",
      "query": "fetch prometheus_target\n| metric 'prometheus.googleapis.com/processing_completed_count_total/counter'\n| align delta(1m)\n| every 1m\n| group_by [],\n    [value_processing_completed_count_total_aggregate:\n       aggregate(value.processing_completed_count_total)]"
     }
    }
   ]
  },
  {
   "title": "Totals and Peaks",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS \"Platform Total\"\nFROM\n  bc.mail_envelope\nWHERE\n  $__timeFilter(created_at)\n  AND org_id IN ($org)\n  AND saga_classification IN ($intent);"
    },
    {
     "rawSql": "SELECT\n  bucket_count || ' @ ' || \n  TO_CHAR(time AT TIME ZONE 'Europe/Copenhagen', 'HH24:MI') || '-' || \n  TO_CHAR((time + '$time_interval'::interval) AT TIME ZONE 'Europe/Copenhagen', 'HH24:MI') AS \"Platform Peak\"\nFROM (\n  SELECT\n    DATE_BIN('$time_interval'::interval, sent_at, '1970-01-01'::timestamp) AS time,\n    COUNT(*) AS bucket_count\n  FROM\n    bc.mail_envelope\n  WHERE\n    $__timeFilter(sent_at)\n    AND org_id IN ($org)\n    AND saga_classification IN ($intent)\n  GROUP BY time\n  ORDER BY bucket_count DESC, time ASC\n  LIMIT 1\n) AS subquery;"
    },
    {
     "rawSql": "SELECT\n  COUNT(*) AS \"ML Total\"\nFROM\n  metrics.events\nWHERE\n  event = 'saga_processing_time'\n  AND $__timeFilter(date_time)\n  AND org IN ($org)\n  AND intent IN ($intent)\n  AND (\n      is_qa IS NULL\n      OR is_qa = FALSE\n  );"
    },
    {
     "rawSql": "SELECT\n  bucket_count || ' @ ' || \n  TO_CHAR(time AT TIME ZONE 'Europe/Copenhagen', 'HH24:MI') || '-' || \n  TO_CHAR((time + '$time_interval'::interval) AT TIME ZONE 'Europe/Copenhagen', 'HH24:MI') AS \"ML Peak\"\nFROM (\n  SELECT\n    DATE_BIN('$time_interval'::interval, date_time, '1970-01-01'::timestamp) AS time,\n    COUNT(*) AS bucket_count\n  FROM\n    metrics.events\n  WHERE\n    event = 'saga_processing_time'\n    AND $__timeFilter(date_time)\n    AND org IN ($org)\n    AND intent IN ($intent)\n    AND (\n      is_qa IS NULL\n      OR is_qa = FALSE\n    )\n  GROUP BY time\n  ORDER BY bucket_count DESC, time ASC\n  LIMIT 1\n) AS subquery;"
    }
   ]
  },
  {
   "title": "Classification duration (Orchestrator)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "timeSeriesQuery": {
      "graphPeriod": "$time_interval",
      "projectName": "api-sandbox-goauto-11",
      "query": "fetch prometheus_target\n| metric\n    'prometheus.googleapis.com/classification_duration_milliseconds/histogram'\n| align delta(1m)\n| every 1m\n| group_by [],\n    [AvgDuration:\n       mean(value.classification_duration_milliseconds)]"
     }
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "jq-backend",
     "root_selector": ".[] | \n  { \"Name\": .name, \"Processing\": .fetched }",
     "source": "url",
     "type": "json",
     "url": "/v1/hangfire/queues",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "Queue size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Queue size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "select queue_name, queue_size, measured_at\nfrom platform.queue_status qs \norder by measured_at desc\n"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "jq-backend",
     "root_selector": ".[] | \n  { \"Name\": .name, \"Queued\": .length }",
     "source": "url",
     "type": "json",
     "url": "/v1/hangfire/queues",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "Error rates and slowdowns", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Requests exceeding threshold",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 55 },
   "targets": [
    {
     "dataset": "ml-db",
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time, $__interval),\n  count(*) AS below\nFROM\n  metrics.events\nWHERE\n  event = 'saga_processing_time'\n  AND $__timeFilter(date_time)\n  AND org IN ($org)\n  AND intent IN ($intent)\n  AND (\n      is_qa IS NULL\n      OR is_qa = FALSE\n    )\n  AND CAST(value AS DECIMAL(10, 3)) < EXTRACT(\n    epoch\n    FROM\n      INTERVAL '$threshold'\n  )\nGROUP BY 1\nORDER BY 1;"
    },
    {
     "dataset": "ml-db",
     "rawSql": "SELECT\n  $__timeGroupAlias(date_time, $__interval),\n  count(*) AS over\nFROM\n  metrics.events\nWHERE\n  event = 'saga_processing_time'\n  AND $__timeFilter(date_time)\n  AND org IN ($org)\n  AND intent IN ($intent)\n  AND (\n      is_qa IS NULL\n      OR is_qa = FALSE\n    )\n  AND CAST(value AS DECIMAL(10, 3)) > EXTRACT(\n    epoch\n    FROM\n      INTERVAL '$threshold'\n  )\nGROUP BY 1\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Count time exceeding threshold",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ml-db",
     "rawSql": "WITH time_series AS (\n  SELECT\n    GENERATE_SERIES(\n      $__timeFrom() :: timestamp,\n      $__timeTo() :: timestamp,\n      '$time_interval' :: interval\n    ) AS date_time\n),\nevents_data AS (\n  SELECT\n    DATE_BIN('$time_interval', date_time, '2000-1-1') AS time,\n    PERCENTILE_CONT(0.50) WITHIN GROUP (\n      ORDER BY\n        CAST(value AS DECIMAL(10, 3))\n    ) AS median\n  FROM\n    metrics.events\n  WHERE\n    event = 'saga_processing_time'\n    AND $__timeFilter(date_time)\n    AND org IN ($org)\n    AND intent IN ($intent)\n    AND (\n      is_qa IS NULL\n      OR is_qa = FALSE\n    )\n  GROUP BY\n    time\n),\ncount_result AS (\n  SELECT\n    COUNT(*) AS median\n  FROM\n    time_series\n    LEFT JOIN events_data ON DATE_BIN('$time_interval', date_time, '2000-1-1') = time\n  WHERE\n    median > EXTRACT(\n      epoch\n      FROM\n        INTERVAL '$threshold'\n    )\n)\nSELECT\n  median\nFROM\n  count_result\nWHERE\n  'median' IN ($metric);"
    },
    {
     "dataset": "ml-db",
     "rawSql": "WITH time_series AS (\n  SELECT\n    GENERATE_SERIES(\n      $__timeFrom() :: timestamp,\n      $__timeTo() :: timestamp,\n      '$time_interval' :: interval\n    ) AS date_time\n),\nevents_data AS (\n  SELECT\n    DATE_BIN('$time_interval', date_time, '2000-1-1') AS time,\n    PERCENTILE_CONT(0.80) WITHIN GROUP (\n      ORDER BY\n        CAST(value AS DECIMAL(10, 3))\n    ) AS p80\n  FROM\n    metrics.events\n  WHERE\n    event = 'saga_processing_time'\n    AND $__timeFilter(date_time)\n    AND org IN ($org)\n    AND intent IN ($intent)\n    AND (\n      is_qa IS NULL\n      OR is_qa = FALSE\n    )\n  GROUP BY\n    time\n),\ncount_result AS (\n  SELECT\n    COUNT(*) AS p80\n  FROM\n    time_series\n    LEFT JOIN events_data ON DATE_BIN('$time_interval', date_time, '2000-1-1') = time\n  WHERE\n    p80 > EXTRACT(\n      epoch\n      FROM\n        INTERVAL '$threshold'\n    )\n)\nSELECT\n  p80\nFROM\n  count_result\nWHERE\n  'p80' IN ($metric);"
    },
    {
     "dataset": "ml-db",
     "rawSql": "WITH time_series AS (\n  SELECT\n    GENERATE_SERIES(\n      $__timeFrom() :: timestamp,\n      $__timeTo() :: timestamp,\n      '$time_interval' :: interval\n    ) AS date_time\n),\nevents_data AS (\n  SELECT\n    DATE_BIN('$time_interval', date_time, '2000-1-1') AS time,\n    PERCENTILE_CONT(0.90) WITHIN GROUP (\n      ORDER BY\n        CAST(value AS DECIMAL(10, 3))\n    ) AS p90\n  FROM\n    metrics.events\n  WHERE\n    event = 'saga_processing_time'\n    AND $__timeFilter(date_time)\n    AND org IN ($org)\n    AND intent IN ($intent)\n    AND (\n      is_qa IS NULL\n      OR is_qa = FALSE\n    )\n  GROUP BY\n    time\n),\ncount_result AS (\n  SELECT\n    COUNT(*) AS p90\n  FROM\n    time_series\n    LEFT JOIN events_data ON DATE_BIN('$time_interval', date_time, '2000-1-1') = time\n  WHERE\n    p90 > EXTRACT(\n      epoch\n      FROM\n        INTERVAL '$threshold'\n    )\n)\nSELECT\n  p90\nFROM\n  count_result\nWHERE\n  'p90' IN ($metric);"
    },
    {
     "dataset": "ml-db",
     "rawSql": "WITH time_series AS (\n  SELECT\n    GENERATE_SERIES(\n      $__timeFrom() :: timestamp,\n      $__timeTo() :: timestamp,\n      '$time_interval' :: interval\n    ) AS date_time\n),\nevents_data AS (\n  SELECT\n    DATE_BIN('$time_interval', date_time, '2000-1-1') AS time,\n    PERCENTILE_CONT(0.95) WITHIN GROUP (\n      ORDER BY\n        CAST(value AS DECIMAL(10, 3))\n    ) AS p95\n  FROM\n    metrics.events\n  WHERE\n    event = 'saga_processing_time'\n    AND $__timeFilter(date_time)\n    AND org IN ($org)\n    AND intent IN ($intent)\n    AND (\n      is_qa IS NULL\n      OR is_qa = FALSE\n    )\n  GROUP BY\n    time\n),\ncount_result AS (\n  SELECT\n    COUNT(*) AS p95\n  FROM\n    time_series\n    LEFT JOIN events_data ON DATE_BIN('$time_interval', date_time, '2000-1-1') = time\n  WHERE\n    p95 > EXTRACT(\n      epoch\n      FROM\n        INTERVAL '$threshold'\n    )\n)\nSELECT\n  p95\nFROM\n  count_result\nWHERE\n  'p95' IN ($metric);"
    },
    {
     "dataset": "ml-db",
     "rawSql": "WITH time_series AS (\n  SELECT\n    GENERATE_SERIES(\n      $__timeFrom() :: timestamp,\n      $__timeTo() :: timestamp,\n      '$time_interval' :: interval\n    ) AS date_time\n),\nevents_data AS (\n  SELECT\n    DATE_BIN('$time_interval', date_time, '2000-1-1') AS time,\n    PERCENTILE_CONT(0.99) WITHIN GROUP (\n      ORDER BY\n        CAST(value AS DECIMAL(10, 3))\n    ) AS p99\n  FROM\n    metrics.events\n  WHERE\n    event = 'saga_processing_time'\n    AND $__timeFilter(date_time)\n    AND org IN ($org)\n    AND intent IN ($intent)\n    AND (\n      is_qa IS NULL\n      OR is_qa = FALSE\n    )\n  GROUP BY\n    time\n),\ncount_result AS (\n  SELECT\n    COUNT(*) AS p99\n  FROM\n    time_series\n    LEFT JOIN events_data ON DATE_BIN('$time_interval', date_time, '2000-1-1') = time\n  WHERE\n    p99 > EXTRACT(\n      epoch\n      FROM\n        INTERVAL '$threshold'\n    )\n)\nSELECT\n  p99\nFROM\n  count_result\nWHERE\n  'p99' IN ($metric);"
    },
    {
     "dataset": "ml-db",
     "rawSql": "WITH time_series AS (\n  SELECT\n    GENERATE_SERIES(\n      $__timeFrom() :: timestamp,\n      $__timeTo() :: timestamp,\n      '$time_interval' :: interval\n    ) AS date_time\n)\nSELECT\n  COUNT(*) as total\nFROM\n  time_series;"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 62 },
   "targets": [
    {
     "aliasBy": "Errors/s",
     "timeSeriesQuery": {
      "projectName": "api-sandbox-goauto-11",
      "query": "fetch cloud_run_revision\n| metric 'logging.googleapis.com/user/error_count_per_second'\n| align rate(1m)\n| every 1m\n| group_by [],\n    [value_error_count_per_second_aggregate:\n       aggregate(value.error_count_per_second)]"
     }
    },
    {
     "aliasBy": "Mail processing errors/s",
     "timeSeriesQuery": {
      "projectName": "api-sandbox-goauto-11",
      "query": "fetch prometheus_target\n| metric 'prometheus.googleapis.com/processing_errors_count_total/counter'\n| align rate(1m)\n| every 1m\n| group_by [],\n    [value_processing_errors_count_total_aggregate:\n       aggregate(value.processing_errors_count_total)]"
     }
    }
   ]
  },
  {
   "title": "Avg mail processing error rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "timeSeriesList": {
      "filters": [],
      "projectName": "api-sandbox-goauto-11",
      "view": "FULL"
     }
    }
   ]
  },
  { "title": "Traffic health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "% of succesfull calls (HTTP, gRPC)",
   "type": "stat",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "last_over_time(\n  (\n    (\n      sum by (service_basename) (\n        label_replace(\n          rate(istio_requests_total{\n            reporter=\"destination\",\n            request_path!~\"/metrics|/|/events|.*/readyz|.*/livez|.*/healthz|.*/openapi*|.*/metrics\",\n            response_code!~\"[45].*\",\n            grpc_response_status!~\"[1-9].+\"\n          }[$__rate_interval]),\n          \"service_basename\", \"$1\", \"destination_service\", \"([a-z-]*[a-z]).*\"\n        )\n      ) \n      / \n      (\n        sum by (service_basename) (\n          label_replace(\n            rate(istio_requests_total{\n              reporter=\"destination\",\n              request_path!~\"/metrics|/|/events|.*/readyz|.*/livez|.*/healthz|.*/openapi*|.*/metrics\"\n            }[$__rate_interval]),\n            \"service_basename\", \"$1\", \"destination_service\", \"([a-z-]*[a-z]).*\"\n          )\n        ) > 0\n      )\n    ) * 100\n  )[2h:]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Customer Perceived Latency",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "gadev",
     "rawSql": "SELECT\n  org_id,\n  -- Return pure seconds so Grafana can calculate thresholds\n  EXTRACT(EPOCH FROM (NOW() - MIN(created_at))) AS delay_seconds\nFROM\n  bc.mail_envelope me\nWHERE\n  org_id IN ($org)\n  AND org_id NOT LIKE '%\\_shadow%'\n  AND (intent IN ($intent) OR intent = 'unknown')\n  AND created_at >= NOW() - INTERVAL '1 hours'\n  AND NOT EXISTS (\n    SELECT 1\n    FROM bc.events e\n    WHERE e.mail_envelope_id = me.mail_envelope_id\n      AND e.event_type = 'process_completed'\n  )\n  AND status = 'processing'\n  --AND EXISTS (\n  --  SELECT 1\n  --  FROM bc.events e\n  --  WHERE e.mail_envelope_id = me.mail_envelope_id\n  --)\nGROUP BY \n  org_id\nHAVING \n  NOW() - MIN(created_at) > INTERVAL '0 seconds'\n  -- AND MAX(created_at) - MIN(created_at) FILTER (WHERE status IN ('processing', 'needs_action')) < INTERVAL '1 day'\nORDER BY \n  delay_seconds DESC;"
    }
   ]
  },
  { "title": "Orchestrator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "Cloud run errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 83 },
   "targets": [
    {
     "timeSeriesQuery": {
      "graphPeriod": "$time_interval",
      "projectName": "api-sandbox-goauto-11",
      "query": "fetch cloud_run_revision\n| metric 'logging.googleapis.com/log_entry_count'\n| filter (metric.severity > 'INFO|NOTICE')\n| align rate(1m)\n| every 1m\n| group_by [resource.service_name],\n    [value_log_entry_count_aggregate: aggregate(value.log_entry_count)]"
     }
    }
   ]
  },
  {
   "title": "Cloud Run Revision - Log entries/s for ERROR|CRITICAL [SUM]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "promQLQuery": {
      "expr": "sum by (service_name) (\n  rate(logging_googleapis_com:log_entry_count{\n    monitored_resource=\"cloud_run_revision\", \n    severity=~\"ERROR|CRITICAL\"\n  }[1m])\n)",
      "projectName": "api-sandbox-goauto-11",
      "step": "10s"
     },
     "timeSeriesList": {
      "filters": [],
      "projectName": "api-prod-goauto-1",
      "view": "FULL"
     }
    }
   ]
  },
  {
   "title": "Cloud run request latencies per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 91 },
   "targets": [
    {
     "aliasBy": "{{resource.label.service_name}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "filters": [
       "metric.type",
       "=",
       "run.googleapis.com/request_latencies"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "api-sandbox-goauto-11"
     }
    }
   ]
  },
  {
   "title": "Memory available",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (path,host)(min_over_time(disk_free{project='sandbox-goauto-3',service='postgres-euw4'}[$__interval])) ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cloud run CPU utilization per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 99 },
   "targets": [
    {
     "aliasBy": "{{resource.label.service_name}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "filters": [
       "metric.type",
       "=",
       "run.googleapis.com/container/cpu/utilizations"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "api-sandbox-goauto-11"
     }
    }
   ]
  },
  {
   "title": "Memory available",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (host)(min_over_time(mem_available{project='sandbox-goauto-3',service='postgres-euw4'}[$__interval])) ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Cloud run RAM utilization per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 107 },
   "targets": [
    {
     "aliasBy": "{{resource.label.service_name}}",
     "timeSeriesList": {
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_PERCENTILE_99",
      "filters": [
       "metric.type",
       "=",
       "run.googleapis.com/container/memory/utilizations"
      ],
      "groupBys": [ "resource.label.service_name" ],
      "perSeriesAligner": "ALIGN_DELTA",
      "preprocessor": "none",
      "projectName": "api-sandbox-goauto-11"
     }
    }
   ]
  },
  {
   "title": "Load average (1 min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 107 },
   "targets": [
    {
     "expr": "max by (host)(max_over_time(system_load1{project='sandbox-goauto-3',service='postgres-euw4'}[$__interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Older running query age",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "avg by (host,datname,role)(avg_over_time(postgresql_pg_stat_activity_oldest_running_query_age{datname!=')',project='sandbox-goauto-3',service='postgres-euw4'}[$__interval])) ",
     "legendFormat": "{{ host }}.{{ datname }}.{{ role }}"
    }
   ]
  }
 ]
}