{
 "title": "Namespaces",
 "description": "【English version】2025.01.25 Updates，kubernetesComprehensive display of resources！Includes K8S Overall Resource Overview、Microservices Resource Details、Pod Resource Details andK8SNetwork Bandwidth，Optimization metrics。https://grafana.com/orgs/starsliao/dashboards",
 "tags": [
  "Prometheus",
  "Kubernetes",
  "namespace"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "node",
    "label": "Nodes",
    "query": {
     "query": "label_values(kube_node_info,node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current Resource Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}/100000) by (container))"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}[2m])) by (container)",
     "legendFormat": "Total Cores Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)/ sum(container_spec_memory_limit_bytes{container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
    },
    {
     "expr": "sum (container_memory_rss{container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$datasource\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)",
     "legendFormat": "Average Memory%(RSS)"
    },
    {
     "expr": "sum (container_memory_rss{container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)",
     "legendFormat": "Total Memory Usage (RSS) "
    },
    {
     "expr": "sum by(container) (kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"})"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
    },
    {
     "expr": "avg(container_fs_usage_bytes{container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
    },
    {
     "expr": "count(kube_pod_container_info{container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by(container)"
    },
    {
     "expr": "avg(container_fs_limit_bytes{container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
    }
   ]
  },
  {
   "title": "PVC Storage Usage",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "{{namespace}}:{{ persistentvolumeclaim }}"
    },
    {
     "expr": "min by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"}) + max by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}) /(min by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=~\"$namespace\"}) + max by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\"}))*100",
     "legendFormat": "{{namespace}}:{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Pod Containers CPU Utilization (Maximum100%Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m])) by (container, pod) / (max(container_spec_cpu_quota{container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}/100000) by (container, pod)) * 100 < 1000",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Container Memory Usage (Associatable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max (container_memory_working_set_bytes{container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod)/ max(container_spec_memory_limit_bytes{container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod) * 100",
     "legendFormat": "WSS：{{ pod }}"
    },
    {
     "expr": "max (container_memory_rss{container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod)/ max(container_spec_memory_limit_bytes{container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod) * 100",
     "legendFormat": "RSS：{{ pod }}"
    }
   ]
  }
 ]
}