apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 8.5.5
  name: grafana-config
  namespace: monitoring
stringData:
  grafana.ini: |
    [server]
    domain = https://grafana.prod.goautonomous.ai/
    root_url = https://grafana.prod.goautonomous.ai/

    [date_formats]
    default_timezone = UTC+01:00

    [auth.google]
    enabled = true
    client_id = 921266374863-qeuib67cdpni05fdd6vjp6pfv6u9rblp.apps.googleusercontent.com
    client_secret = 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
    scopes = https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
    auth_url = https://accounts.google.com/o/oauth2/auth
    token_url = https://accounts.google.com/o/oauth2/token
    allowed_domains = goautonomous.io goautonomous.ai
    allow_sign_up = true

    [smtp]
    enabled = true
    host = smtp.sendgrid.net:465
    user = apikey
    password = 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
    skip_verify = false
    from_address = grafana@goautonomous.io
    from_name = Grafana

type: Opaque
